spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/user-service
    username: sa
    password: 123

  jpa:
    hibernate:
      ddlAuto: create-drop
    databasePlatform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
server:
  port: 8083



jwt:
  time: 1800
  service-type: user
  secret: REVGQVVMVERFRkFVTFRERUZBVUxUREVGQVVMVERFRkFVTFRERUZBVUxUREVGQVVMVERFRkFVTFRERUZBVUxUREVGQVVMVA==

logging:
  level:
    com.c9Pay.userservice: debug