spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:user-service
    username: ENC(yrUMw+QE8Br4j+ZJf5R/RA==)
    password: #ENC(qyVsfasFWRdgcYn/XoQVqg==)

  jpa:
    hibernate:
      ddlAuto: create
    databasePlatform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
server:
  port: 8083



jwt:
  time: ENC(7R/Ski8G2Mi4k+uprAwLuQ==)
  service-type: ENC(9vruXpL+mRox/n5yyNkQmg==)
  secret: ENC(50PmC8wTPcUAcv8fh1XLM+eMhqMQsOuNhOJG3X8wgJ4HP62Q8h8+FlIlvUV81cifTkH+ym7RkB3lzOJJ4MX5WJ0QjvN1y2B/AKyQGNZvFD9/zp2G29osZKQX/ZtkR4OzjSMTpOaofZEJnG1L3+Ha5Q==)
rsa:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlBv2x56fah4U18XT6m2hnAOHxUqTriqiWWdOJMY13YQJ6Su1EMWxwPC369yqUA30oiOfJ9qM5T5rBmdj/ydav1hit6WXHK7kUYS5ldSlUPlprl76HeGNyCbSzuyVORo6e7X+nYlivUf4+6vobCCnLYJHdPOdEWHZOCQB8eXYyAYN9uGSv3HPeltr6qV4Cs4yO2Z2Gn9XaTKhfqYqanjyfRWkBNJ5j7MKU+zpSGmfvoCvWWgIHI+StY67vOKRrmOFJoDNSYkPql0XNPQcmwDeeG1eahlv8LL+/mJ0uXb734ahc/g3FiyNr2qgGowJEkmW7UEhdlKdd87CVX6TzSMSqwIDAQAB
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCUG/bHnp9qHhTXxdPqbaGcA4fFSpOuKqJZZ04kxjXdhAnpK7UQxbHA8Lfr3KpQDfSiI58n2ozlPmsGZ2P/J1q/WGK3pZccruRRhLmV1KVQ+WmuXvod4Y3IJtLO7JU5Gjp7tf6diWK9R/j7q+hsIKctgkd0850RYdk4JAHx5djIBg324ZK/cc96W2vqpXgKzjI7ZnYaf1dpMqF+pipqePJ9FaQE0nmPswpT7OlIaZ++gK9ZaAgcj5K1jru84pGuY4UmgM1JiQ+qXRc09BybAN54bV5qGW/wsv7+YnS5dvvfhqFz+DcWLI2vaqAajAkSSZbtQSF2Up13zsJVfpPNIxKrAgMBAAECggEAKjO1o7etEN21bq4t7hSDAiN3Yl4Xqn73d6YZ/ByGaLIg6NHNbBQIzENLBOgBl4ICfNjNltuNXhzk/hQjyCZ8kx0qM835OvESma/J+cl3uZT36fmiJzWH4so9MzzyYCz7ERkQje8BtZF2fq/DMFw1hqAioE5yKOvKq1aHP1gQ5x1zjaWhAhpclE8jeuVHXFTiePBlnYvBJHyqD19pg1x5Tud6oT74H415ciInITcA93r6mhCY+0olUa3hTrCQQSaiIL54qpY82spOQGlwaGnqqR0y7rLrMjjF7wcKRT3Uqfk9yRVkosftlyS6yJIeWW/t9S+P7QOFScmFQWksNYtAEQKBgQC/nBzyAh2rQA5kqQOiC95/JHzgFdvlpGjYSV0wjpwnSFueZzAa21wmDuXcUn4DWyM+Sp0Y7+0N/IV/ejspZeDzsy7SDjmG+yAy1JNntHkH1eAWkQVHO6KE/4HkoSLHWE0DyYP7ez9wjr8dC+45J8qFtDdahFmltkvEvQtXuvb7twKBgQDF4ZCwiTBMDn25qd0/LQW0fX94tZL7+oCZsU2R701Hou93MqDJ0ZKC/yUjV5uvfeD2tItWin94XBnIP3KkfyQ7wD8SOIBtcc5bThgl3SY3YNVVgOCyfla/CU9eKdHxy8VXHYmtagFQy6SaiUx6dfeFn51hG4umHXzAogpd5QzIrQKBgQCLrGQZMduowuf7Do08acSGD/YLb0O9cYyP5WLOC5bet8s5e+TAHxlcEM4UPfnnvl7BgKhlzjeSU3qJA3Pu6HoDi6Fcs8vRjmvZQcY1+YOkZ46TRKGBXIJKyupH3AI7KC3zzcis4BnNlfDQXqsH9O6XalhTXljvCCTRRDDpgbuanwKBgQCf/OaaBOFarOCzywXJvWH+cvUsKEollnyBRtv7oKovwCmyiul7Iwk9BoMFVyDVu4W2kXSSzLmRG43w3HOZUf5+nMmhtrMHSdtY8QQPIQV0AsOZNPD2/7StEh7seA15XJI6A/S7k5hqtatpEpcV7+jnTYzV5Yp8DR0/NgQBtF4opQKBgBnTkkv0bvrLDcsflzEktdZl6epCYnG1K8ZjyzpyA8f1u2yASf2ZT/JJftIpy7cTg2ghgEf9CnvDOG3BW7+fJDWxMyifFer23aw21OYAQVBSgXXgIoEnxviLHUyK1rdYWx37kWhrBRNvePeGTTVuZY1IbFLNAH9bokFl4M8jqoXK

logging:
  level:
    com.c9Pay.userservice: debug
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3, w3c
      produce: b3, w3c
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
