spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:user-service
    username: ENC(yrUMw+QE8Br4j+ZJf5R/RA==)
    password: #ENC(qyVsfasFWRdgcYn/XoQVqg==)

  jpa:
    hibernate:
      ddlAuto: create-drop
    databasePlatform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
server:
  port: 8083



jwt:
  time: ENC(fUvyjIJO2khbDxBL+a+pfg==)
  service-type: ENC(9vruXpL+mRox/n5yyNkQmg==)
  secret: ENC(50PmC8wTPcUAcv8fh1XLM+eMhqMQsOuNhOJG3X8wgJ4HP62Q8h8+FlIlvUV81cifTkH+ym7RkB3lzOJJ4MX5WJ0QjvN1y2B/AKyQGNZvFD9/zp2G29osZKQX/ZtkR4OzjSMTpOaofZEJnG1L3+Ha5Q==)

logging:
  level:
    com.c9Pay.userservice: debug