spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:user-service
    username: ENC(yrUMw+QE8Br4j+ZJf5R/RA==)
    password: #ENC(qyVsfasFWRdgcYn/XoQVqg==)

  jpa:
    hibernate:
      ddlAuto: create
    databasePlatform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
jwt:
  time: ENC(7R/Ski8G2Mi4k+uprAwLuQ==)
  service-type: ENC(9vruXpL+mRox/n5yyNkQmg==)
  secret: ENC(50PmC8wTPcUAcv8fh1XLM+eMhqMQsOuNhOJG3X8wgJ4HP62Q8h8+FlIlvUV81cifTkH+ym7RkB3lzOJJ4MX5WJ0QjvN1y2B/AKyQGNZvFD9/zp2G29osZKQX/ZtkR4OzjSMTpOaofZEJnG1L3+Ha5Q==)
logging:
  level:
    com.c9Pay.userservice: debug
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3, w3c
      produce: b3, w3c
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
