spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: ENC(QlYAYNFz1Wqe++xMrypTlnwsZoCsj2u5YDqnSXA+Q43cjgoLBndeLiYqe8jQ3avIyOd0adEhN7Xs/zdLdVwKj3HRDcerK1BlZGx/6An3JEZGy51syStj66jYwTFRGSxf)
    username: ENC(P0YpE5s27eFW0hFCz2OxjGndSH6aje0r)
    password: ENC(P0YpE5s27eFW0hFCz2OxjGndSH6aje0r)
  jpa:
    hibernate:
      ddlAuto: validate
    defer-datasource-initialization: true

server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
jwt:
  time: 1800000
  service-type: ENC(9vruXpL+mRox/n5yyNkQmg==)
  secret: ENC(50PmC8wTPcUAcv8fh1XLM+eMhqMQsOuNhOJG3X8wgJ4HP62Q8h8+FlIlvUV81cifTkH+ym7RkB3lzOJJ4MX5WJ0QjvN1y2B/AKyQGNZvFD9/zp2G29osZKQX/ZtkR4OzjSMTpOaofZEJnG1L3+Ha5Q==)
logging:
  level:
    com.c9Pay.userservice: debug
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3, w3c
      produce: b3, w3c
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

springdoc:
  packages-to-scan: com.c9Pay.userservice.web.mvc.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /user-service/api/docs
    display-request-duration: true
    disable-swagger-default-url: true
    operations-sorter: alpha
