
### 사용자 정보 업데이트
PUT {{user-api}}/api/user
Content-Type: application/json
Cookie: Authorization=Bearer+eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkxMTExOTA2LCJleHAiOjE2OTExMTI2NTZ9.tof3Nl5sqP3-GlQ5jVSOTaioUAT1w-GGzo_k3no8WwOjKW4g7ddjThXIE_T_iHOLmIjGbUzAV4t2wAkFouXmNg

{
  "username": "vv",
  "email":"aaa@bbb.ccc",
  "userId": "vvv3",
  "password": "v2v"
}

### 회원가입
POST {{user-api}}/api/user/signup
Content-Type: application/json

{
  "userId":"vv22",
  "username": "dummy",
  "password": "vv",
  "email": "abd@gmail.com"
}


### 사용자 정보
GET {{user-api}}/api/user
Cookie: Authorization=Bearer+eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjkxMTEyNDkyLCJleHAiOjE2OTExMTMyNDJ9.5l1BcraJYchi9i2dVAz2n2dBbG6XdMuczMUisvSnDbOilixyZrPuqzGmMucfUvH1j0XFULwQAYZv8RVkBqQXVA

### 아이디 중복 확인
GET {{user-api}}/api/user/check-duplicate
userId: vv2


### 사용자 개체 식별번호 조회
GET {{user-api}}/user/serial-number
cookie: Authorization=Bearer+eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNjkxMDU3ODE4LCJleHAiOjE2OTEwNTg1Njh9.DTj8tyZDMtqawEE39yXjR9e_h91snKN2ZI3p7mCQI2MlPPzYZ0HtfpX1NMQTkz3C8eMmUNudgam8ZDUnnIaxdQ

### 사용자 삭제
DELETE {{user-api}}/api/user
cookie:  Authorization=Bearer+eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNjkxMDU3MzYzLCJleHAiOjE2OTEwNTgxMTN9.zLQpk34_Gy_yjgbgx3mVN8PNrQAODl4tNqtfDIZJ5vPQp9Cgt_SAj99xRcDohFuoY4YW8zAjrJHo4Ao8MpVzuw